name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN_NOSCOPE }}
          retries: 3
          retries_delay: 300
          output_action: pull-request
          base: ""
          filename: interesting-facts-and-stars.svg
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: no
          plugin_stars: yes
          plugin_stars_limit: 3
          config_timezone: America/Los_angeles
          config_order: habits, stars
          
      - uses: lowlighter/metrics@latest
        with:
          retries: 3
          retries_delay: 300
          output_action: pull-request
          base: ""
          filename: today-fortune.svg
          plugin_fortune: yes
      
      - uses: lowlighter/metrics@latest
        with:
          retries: 3
          retries_delay: 300
          output_action: pull-request-merge
          base: ""
          filename: leetcode-data.svg
          plugin_leetcode: yes
          plugin_leetcode_sections: solved, skills
          
        
